(function(){
const $=id=>document.getElementById(id),LSg=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},LSs=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const d=()=>($('date')&&$('date').value)||new Date().toISOString().slice(0,10),key=x=>'kc-fitness-'+x,load=(x=d())=>LSg(key(x),{steps:0,active:0,exercise:0,distance:0}),save=(v,x=d())=>LSs(key(x),v);
function last7(){let a=[];for(let i=6;i>=0;i--){let x=new Date();x.setDate(x.getDate()-i);a.push(x.toISOString().slice(0,10))}return a}
function refresh(){let v=load();[['todaySteps','steps'],['todayActive','active'],['todayExercise','exercise'],['fitSteps','steps'],['fitActive','active'],['fitExercise','exercise']].forEach(([id,k])=>{if($(id))$(id).textContent=k==='steps'?Math.round(v[k]||0).toLocaleString('de-DE'):Math.round(v[k]||0)});if($('fitDistance'))$('fitDistance').textContent=(+v.distance||0).toFixed(1);if($('stepsInput'))$('stepsInput').value=v.steps||'';if($('activeInput'))$('activeInput').value=v.active||'';if($('exerciseInput'))$('exerciseInput').value=v.exercise||'';if($('distanceInput'))$('distanceInput').value=v.distance||'';if($('creditActive'))$('creditActive').checked=LSg('kc-credit-active',false);let base=+$('goal')?.value||2000,used=+$('used')?.textContent||0,budget=base+(LSg('kc-credit-active',false)?(+v.active||0):0);if($('left'))$('left').textContent=Math.round(budget-used);if($('fitnessWeek')){let rows=last7().map(x=>({x,v:load(x)})),m=Math.max(1,...rows.map(r=>+r.v.steps||0));$('fitnessWeek').innerHTML=rows.map(r=>`<div class="fitness-week-row"><span>${new Date(r.x+'T12:00').toLocaleDateString('de-DE',{weekday:'short',day:'2-digit'})}</span><div class="fitness-week-bar"><i style="width:${Math.min(100,(+r.v.steps||0)/m*100)}%"></i></div><b>${Math.round(r.v.steps||0).toLocaleString('de-DE')}</b></div>`).join('')}}
if($('saveFitness'))$('saveFitness').onclick=()=>{save({steps:+$('stepsInput').value||0,active:+$('activeInput').value||0,exercise:+$('exerciseInput').value||0,distance:+$('distanceInput').value||0});refresh();alert('Fitnesswerte gespeichert.')};
if($('openFitness'))$('openFitness').onclick=()=>document.querySelector('[data-t="fitness"]')?.click();
if($('creditActive'))$('creditActive').onchange=()=>{LSs('kc-credit-active',$('creditActive').checked);refresh()};
if($('copyFitnessLink'))$('copyFitnessLink').onclick=async()=>{let t=location.origin+location.pathname+'?fitness=1&steps=[SCHRITTE]&active=[AKTIVKALORIEN]&exercise=[TRAININGSMINUTEN]&distance=[DISTANZ_KM]';try{await navigator.clipboard.writeText(t);$('fitnessCopyMsg').textContent='Link-Vorlage kopiert.'}catch{$('fitnessCopyMsg').textContent=t}};
let sp=new URLSearchParams(location.search);if(sp.get('fitness')==='1'||['steps','active','exercise','distance'].some(k=>sp.has(k))){let x=sp.get('date')||new Date().toISOString().slice(0,10),o=load(x);save({steps:sp.has('steps')?+sp.get('steps')||0:o.steps,active:sp.has('active')?+sp.get('active')||0:o.active,exercise:sp.has('exercise')?+sp.get('exercise')||0:o.exercise,distance:sp.has('distance')?+sp.get('distance')||0:o.distance},x);document.querySelector('[data-t="fitness"]')?.click();history.replaceState({},'',location.pathname)}
if(typeof window.render==='function'){const old=window.render;window.render=function(){old();refresh()}}
$('date')?.addEventListener('change',refresh);setTimeout(refresh,100);
})();